#!/bin/bash

if [ $# == 0 ]
then
    echo "usage: deployarduinolib <lib name> <-d: delete the lib>"
    exit
fi

if [ "$2" == "-d" ]
then
    rm -rf "/usr/share/arduino/libraries/"$1    
else
    cp -rf $1 /usr/share/arduino/libraries/
    cd "/usr/share/arduino/libraries/"$1 
    rm *.ino
fi

echo "DONE"



