#!/bin/bash

if [ $# != 1  ]
    then
    echo "upshellconfig <commit msg>"
    exit
fi

commitMsg=$1
shellConfigDir="/home/s/work/shellconfig"
echo $(pwd)
cd $shellConfigDir
echo $(pwd)
echo "updating shell config files"
cp ~/.vimrc             .
cp ~/.bashrc            .
cp ~/.tmux.conf         .
cp -rf ~/.tmux          .

echo $(pwd)
git add .
git commit -m '$commitMsg'
git push origin master

